TOP_STOCKS = [
    {"symbol": "NVDA", "name": "NVIDIA"},
    {"symbol": "AAPL", "name": "Apple"},
    {"symbol": "GOOGL", "name": "Alphabet (Google)"},
    {"symbol": "MSFT", "name": "Microsoft"},
    {"symbol": "AMZN", "name": "Amazon"},
    {"symbol": "TSM", "name": "Taiwan Semiconductor"},
    {"symbol": "AVGO", "name": "Broadcom"},
    {"symbol": "HSBC", "name": "HSBC Holdings"},
    {"symbol": "SPCX", "name": "SpaceX"},
    {"symbol": "META", "name": "Meta Platforms"},
    {"symbol": "TSLA", "name": "Tesla"},
    {"symbol": "BRK-B", "name": "Berkshire Hathaway"},
    {"symbol": "LLY", "name": "Eli Lilly"},
    {"symbol": "MU", "name": "Micron Technology"},
    {"symbol": "JPM", "name": "JPMorgan Chase"},
    {"symbol": "WMT", "name": "Walmart"},
    {"symbol": "AMD", "name": "Advanced Micro Devices"},
    {"symbol": "V", "name": "Visa"},
    {"symbol": "ASML", "name": "ASML Holding"},
    {"symbol": "BP", "name": "BP"},
    {"symbol": "XOM", "name": "Exxon Mobil"},
    {"symbol": "JNJ", "name": "Johnson & Johnson"},
    {"symbol": "PDD", "name": "PDD Holdings"},
    {"symbol": "INTC", "name": "Intel"},
    {"symbol": "MA", "name": "Mastercard"},
    {"symbol": "CSCO", "name": "Cisco Systems"},
    {"symbol": "BHP", "name": "BHP Group"},
    {"symbol": "BAC", "name": "Bank of America"},
    {"symbol": "ABBV", "name": "AbbVie"},
    {"symbol": "AMAT", "name": "Applied Materials"},
    {"symbol": "ORCL", "name": "Oracle"},
    {"symbol": "COST", "name": "Costco Wholesale"},
    {"symbol": "FMX", "name": "Fomento Economico Mexicano"},
    {"symbol": "PLTR", "name": "Palantir Technologies"},
    {"symbol": "NGG", "name": "National Grid"},
    {"symbol": "LRCX", "name": "Lam Research"},
    {"symbol": "CAT", "name": "Caterpillar"},
    {"symbol": "GE", "name": "GE Aerospace"},
    {"symbol": "LYG", "name": "Lloyds Banking Group"},
    {"symbol": "KO", "name": "Coca-Cola"},
]
